# Generated by Django 4.0.6 on 2022-08-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_articles_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='blog_view',
            field=models.IntegerField(default=0),
        ),
    ]
