# Generated by Django 4.0.6 on 2022-08-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_articles_blog_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='region',
            field=models.CharField(choices=[('1', 'Andijon viloyati'), ('2', 'Buxoro viloyati'), ('3', "Farg'ona viloyati"), ('4', 'Jizzax viloyati'), ('5', 'Xorazm viloyati'), ('6', 'Namangan viloyati'), ('7', 'Navoiy viloyati'), ('8', 'Qashqadaryo'), ('9', "Qoraqalpog'iston Respublikasi"), ('10', 'Samarqand viloyati'), ('11', 'Sirdaryo viloyati'), ('12', 'Surxondaryo'), ('13', 'Toshkent viloyati'), ('14', 'Toshkent shahri')], default=14, max_length=35),
        ),
    ]
