# Generated by Django 4.0.6 on 2022-08-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_articles_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='category',
            field=models.CharField(choices=[('1', 'Dunyo'), ('2', "O'zbekiston"), ('3', 'Sport'), ('4', 'Texnologiya'), ('5', 'Ilm-fan'), ('6', "San'at"), ('7', 'Boshqa')], default=1, max_length=35),
        ),
    ]
