# Generated by Django 4.0.6 on 2022-08-21 09:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_articles_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='body',
            field=ckeditor.fields.RichTextField(verbose_name='Maqola matni:'),
        ),
    ]
